# run with `hugo server -D`

# COPY parameters from themes/hugo-book/exampleSite/hugo.toml
# use drafts/ for more on header tags
# DOCS: https://themes.gohugo.io/themes/hugo-book/
# EXAMPLE: https://hugo-book-demo.netlify.app/
# ALL SHORTCODES: https://gohugo.io/content-management/shortcodes/

# when you're ready, publish: 
# https://gohugo.io/hosting-and-deployment/hosting-on-github/

baseURL = 'https://leontoddjohnson.github.io/etc'
languageCode = 'en-us'
title = 'ltj / etc'
theme = 'hugo-book'

[params]
  BookTheme = 'dark'
  BookFavicon = 'groovepaper.png'
  BookRepo = 'https://github.com/leontoddjohnson/etc'
  math = false

[markup.goldmark.renderer]
  unsafe = true